stages:
  - build
  - test


zap-automation-baseline-scan 1/2:
  tags: 
    - gitlab-org-docker
  stage: test
  image: docker:latest
  services:
    - name: docker:dind
      alias: app
  before_script:
    - docker network create mynetwork
    - docker-compose build
    - docker-compose up --detach
  script:
    - docker run --network=mynetwork -v $(pwd):/zap/wrk/:rw owasp/zap2docker-stable zap-baseline.py -t http://app:4000 -r baseline-report.html
  after_script:
    - docker-compose down


    
zap-automation-baseline-scan 2/2:
  tags: 
    - gitlab-org-docker
  image:
    name: owasp/zap2docker-stable:latest
    entrypoint: [""]
  services: 
    - docker:dind
  stage: test
  variables:
    CI_PROJECT_DIR: /builds/filip.st1357/test
    ZAP_ALERT_REPORT: alert-report
    ZAP_REPORT: baselinescan
    DOCKER_HOST: tcp://docker:2375/
  script:
    - hostname -I # Returns the IP address of the machine
    - bash zap_automation_baseline_scan.sh
  only:
    refs:
    - branches
  artifacts:
    when: always
    expire_in: 1 month
    paths:
      - ${CI_PROJECT_DIR}/${ZAP_REPORT}.html
      - ${CI_PROJECT_DIR}/${ZAP_ALERT_REPORT}.md



