stages:
  - build
  - test


zap-automation-baseline-scan 1/2:
  tags: 
    - gitlab-org-docker
  stage: test
  image: docker:latest
  services:
    - docker:dind
  script:
    - hostname -i
    - docker ps
    - docker-compose build
    - docker-compose up --detach
    - docker ps
    - docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-full-scan.py -t https://brokencrystals.com/ -g gen.conf -r testreport.html
    - docker ps

zap-automation-baseline-scan 2/2:
  tags: 
    - gitlab-org-docker
  image:
    name: owasp/zap2docker-stable:latest
    entrypoint: [""]
  services: 
    - docker:dind
  stage: test
  variables:
    CI_PROJECT_DIR: /builds/filip.st1357/test
    ZAP_ALERT_REPORT: alert-report
    ZAP_REPORT: baselinescan
    DOCKER_HOST: tcp://docker:2375/
  script:
    - hostname -I # Returns the IP address of the machine
    - bash zap_automation_baseline_scan.sh
  only:
    refs:
    - branches
  artifacts:
    when: always
    expire_in: 1 month
    paths:
      - ${CI_PROJECT_DIR}/${ZAP_REPORT}.html
      - ${CI_PROJECT_DIR}/${ZAP_ALERT_REPORT}.md



