---
env:
  contexts:
  - name: "Default Context"
    urls:
    - "http://5c5ea741b92e7137_web_1:4000/"
    includePaths: []
    excludePaths: []
    authentication:
      parameters: {}
      verification:
        method: "response"
        pollFrequency: 60
        pollUnits: "requests"
    sessionManagement:
      method: "cookie"
      parameters: {}
    technology:
      exclude: []
  parameters:
    failOnError: true
    failOnWarning: false
    progressToStdout: true
  vars: {}
jobs:
- parameters:
    context: "Default Context"
    user: ""
    url: "http://5c5ea741b92e7137_web_1:4000/"
    maxDuration: 60
    maxCrawlDepth: 10
    numberOfBrowsers: 32
    browserId: "chrome"
    maxCrawlStates: 0
    eventWait: 1
    reloadWait: 1
    clickDefaultElems: true
    clickElemsOnce: true
    randomInputs: true
    inScopeOnly: true
    runOnlyIfModern: false
  name: "spiderAjax"
  type: "spiderAjax"
- parameters:
    maxDuration: 0
  name: "passiveScan-wait"
  type: "passiveScan-wait"

