name: OWASP ZAP SCAN
on: [push]

jobs:
  test:
    name: OWASP ZAP SCANS
    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v2
         with:
          ref: master
       - name: Create Docker Network
         run: |
          docker network create mynetwork
          docker-compose build
          docker-compose up --detach 
          docker ps 
          docker network connect mynetwork docker-compose_application_web_1
          docker network connect mynetwork docker-compose_application_mongo_1
          docker network inspect mynetwork
       - name: Launching the app
         run: docker-compose up --detach
