name: Security Checks
on: [push]

jobs:
  test:
    name: OWASP ZAP SCANS
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        node-version: ["14.x"]
        
    steps:
       - uses: actions/checkout@v2
         with:
            persist-credentials: false 
            ref: master
       - name: Building Docker Node-Goat Image
         run: docker-compose build
       - name: Launching the app
         run: docker-compose up --detach

       - name: OWASP ZAP
         uses: zaproxy/action-baseline@v0.4.0
         with:
           persist-credentials: false 
           target: "http://localhost:4000"
           fail_action: false
           token: $
           issue_title: Security Tests
